trydjango19/posts/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import PostCreateAPIView,PostListAPIView, PostDetailAPIView,PostDeleteAPIView,PostUpdateAPIView
# from .views import  posts_create,posts_delete,posts_detail,posts_list,posts_update
urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^create/$', PostCreateAPIView.as_view(),name="create"),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(),name="delete"),
]

trydjango19/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import  posts_create,posts_delete,posts_detail,posts_list,posts_update
urlpatterns = [
    url(r'^$', posts_list, name='list'),
    url(r'^create/$', posts_create),
    url(r'^(?P<slug>[\w-]+)/$', posts_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', posts_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', posts_delete),
]

trydjango19/trydjango19/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_jwt.views import obtain_jwt_token

from accounts.views import login_view, logout_view, register_view
from posts import views
import posts

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include("posts.urls", namespace="posts")),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trydjango19/posts/models.py
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType

from django.utils.safestring import mark_safe

from django.utils import timezone

from django.core.urlresolvers import reverse
from django.db import models
from  django.db.models.signals import pre_save
# Create your models here.
from django.utils.text import slugify
from    django.conf import settings
from markdown_deux import markdown

from comments.models import Comment
from posts.utils import get_read_time


def upload_location(instance,filename):
    return "%s/%s" %(instance.slug, filename)
class PostManager(models.Manager):
    def active(self,*args, **kwargs):
        return super(PostManager, self).filter(draft = False).filter(publish__lte = timezone.now())


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True,)
    image = models.ImageField(upload_to=upload_location,null=True,blank=True,width_field="width_field",height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    read_time = models.IntegerField(default=0)#TimeField(null=True,blank=True)
    publish = models.DateField(auto_now=False,auto_now_add=False   )
    updated = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)

    objects = PostManager()
    def __unicode__(self):
        return self.title
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("posts:detail",kwargs={"slug":self.slug})
    def get_api_url(self):
        return reverse("posts-api:detail",kwargs={"slug":self.slug})
    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)
    class Meta:
        ordering = ["-timestamp","-updated"]
    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance,new_slug = None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs= Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.first().id)
        return create_slug(instance,new_slug = new_slug)
    return slug
def pre_save_post_receiver(sender,instance,*args,**kwargs):

    if not instance.slug:
        instance.slug = create_slug(instance)
    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time


pre_save.connect(pre_save_post_receiver,sender=Post)

trydjango19/posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget
class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(label="",widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish"
        ]

trydjango19/posts/api/views.py
from django.db.models import Q
from rest_framework.filters import SearchFilter
from rest_framework.generics import RetrieveDestroyAPIView,ListAPIView,RetrieveUpdateAPIView,RetrieveAPIView,UpdateAPIView,DestroyAPIView, CreateAPIView
from rest_framework.pagination import PageNumberPagination, LimitOffsetPagination

from posts.api.pagination import PostLimitOffsetPagination, PostPageNumberPagination
from posts.api.permissions import IsOwnerOrReadOnly
from .serializers import PostListSerializer,PostDetailSerializer,PostCreateUpdateSerializer
from posts.models import Post
from rest_framework.permissions import AllowAny,IsAuthenticated,IsAdminUser, IsAuthenticatedOrReadOnly

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [
        IsAuthenticated
    ]
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = "slug"
    # lookup_url_kwarg = "abc"

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [
        IsAuthenticatedOrReadOnly,
        IsOwnerOrReadOnly,
    ]
    lookup_field = "slug"
    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(RetrieveDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [
        IsAuthenticatedOrReadOnly,
        IsOwnerOrReadOnly,
    ]
    lookup_field = "slug"

class PostListAPIView(ListAPIView):
    # queryset =
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter]
    search_fields = ["title","content","user__first_name"]
    pagination_class = PostPageNumberPagination #PageNumberPagination
    def get_queryset(self,*args,**kwargs):
        # queryset_list = super(PostListAPIView,self).get_query_set(*args,*kwargs)
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            ).distinct()
        return queryset_list

trydjango19/posts/views.py
from django.contrib.contenttypes.models import ContentType

from django.db.models import Q

from django.utils import timezone
from urllib import quote_plus

from django.http import Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages
# Create your views here.
from comments.forms import CommentForm
from comments.models import Comment
from .models import Post
from forms import PostForm


def posts_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    if not request.user.is_authenticated:
        raise  Http404
    form = PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request,"Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form":form,
    }
    return render(request,"post_form.html",context)

def posts_detail(request,slug=None):
    instance  = get_object_or_404(Post,slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    comments = instance.comments#Comment.objects.filter_by_instance(instance)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id,
    }
    form = CommentForm(request.POST or None,initial=initial_data)

    if form.is_valid() and request.user.is_authenticated():
        print(form.cleaned_data)
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model = c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj=None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count()==1:
                parent_obj = parent_qs.first()
        new_comment,created = Comment.objects.get_or_create(
            user = request.user,
            content_type = content_type,
            object_id = obj_id,
            content = content_data,
            parent =parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    context = {
        "instance":instance,
        "title": instance.title,
        "share_tring":share_string,
        "comments":comments,
        "comment_form":form,
    }
    return render(request,"post_detail.html",context)


def posts_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()  # .order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 1)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "List",
        "page_request_var": page_request_var,
        "today": today,
    }
    return render(request, "post_list.html", context)

def posts_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post,slug=slug)
    form = PostForm(request.POST or None,request.FILES or None,instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        print form.cleaned_data.get("title")
        instance.save()
        messages.success(request, "Successfully Saved")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "instance": instance,
        "title": instance.title,
        "form":form
    }
    return render(request,"post_form.html",context)

def posts_delete(request,id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "Successfully Deleted")
    return redirect("posts:list")

trydjango19/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head %}Try django{% endblock head %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/base.css" %}"/>
    <style>
        {% block style %}
        {%  endblock style %}
    </style>
    {% block head_extra %}
    {% endblock head_extra %}
</head>
<body>
<div id="fb-root"></div>
<script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.8";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% include "messages_display.html" %}

<div class="container">
<ol class="breadcrumb">
    <li><a href="{% url "posts:list" %}">Home</a></li>
{% block post_detail_link %}
{% endblock %}
{% if not request.user.is_authenticated %}
    <li class="pull-right"><a href="{% url "register" %}">Register</a></li>
    <li class="pull-right"><a href="{% url "login" %}">Login</a></li>
    {% else%}
    <li class="pull-right"><a href="{% url "logout" %}">Logout</a></li>
    {% endif %}
</ol>

    {% block content %}
    {% endblock content %}
</div>
<!-- Latest compiled and minified JavaScript -->
<script
        src="http://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".content-markdown").each(function () {
            var content = $(this).text()
            console.log(content)
            var markedContent = marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
        })
        $(".post-detail-item img").each(function () {
            $(this).addClass("img-responsive")
        })
        var titleItem = $("#id_title")
        $("#preview-title").text(titleItem.val())
        var contentInput = $("#id_content")

        function setContent(value) {
            var markedContent = marked(value)
            $(".preview-content").html(markedContent)
            $(".preview-content img").each(function () {
                $(this).addClass("img-responsive")
            })
        }

        contentInput.keyup(function () {
            var newContent = $(this).val()
            setContent(newContent)
            console.log(newContent)
        })
        function setTitle(value) {
            $(".preview-title").text(value)
        }

        titleItem.keyup(function () {
            var newTitle = $(this).val()
            setTitle(newTitle)
        })
        $(".comment-reply-btn").click(function (event) {
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle()
        })
    })
</script>
</body>
</html>

trydjango19/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head %}
    {{ instance.title }} | {{ block.super }}
{% endblock head %}
<style>
    {% block style %}
        h1 {
            color: #777777;
        }
    {% endblock style %}
</style>
{% block content %}

    {{ object }}
    <div class="col-sm-6 col-sm-offset-3">
            <p>{{ comment.content }}</p>
            <footer>via {{ comment.user }} | {{ comment.timestamp | timesince }} ago |
                {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}{% endif %}
            {% if request.user == comment.user %} <a href="{{ comment.get_delete_url }}"> | Delete </a>{% endif %}</footer>
        <hr/>
            <div>
                {% for child_comment in comment.children %}
                    <blockquote>
                        <p>{{ child_comment.content }}</p>
                        <footer>via {{ child_comment.user }}
                            | {{ child_comment.timestamp | timesince }} ago {% if request.user == child_comment.user %}| <a href="{{ child_comment.get_delete_url }}"> Delete </a>{% endif %}</footer>
                    </blockquote>
                {% endfor %}
                {% if request.user.is_authenticated %}
                <form method="POST" action="."> {% csrf_token %}
                    {{ form | crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <input type="submit" value="Reply" class="btn btn-default">
                </form>
            {% else %}
                <p> You must login to comment</p>
                {% endif %}
            </div>

        <hr/>
    </div>
{% endblock content %}

trydjango19/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head %}
    {{ instance.title }} | {{ block.super }}
{% endblock head %}
<style>
    {% block style %}
        h1 {
            color: #777777;
        }
    {% endblock style %}
</style>
{% block content %}

    {{ object }}
    <div class="col-sm-6 col-sm-offset-3">
<h1>Confirm Delete</h1>

                <form method="POST" action="."> {% csrf_token %}
                    <p>Are you sure want to delete: "{{ object.content }}"</p>
                    <input type="submit" value="Confirm" class="btn btn-default">
                    <a href="{{ object.get_absolute_url }} " class = "btn btn-default">Cancel</a>
                </form>
            </div>

        <hr/>
    </div>
{% endblock content %}

trydjango19/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }}</h1>
        <hr/>
<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
    {{ form|crispy}}
    <input type="submit" class='btn btn-default' value="{{ title }}"/>
</form>
    </div>
{% endblock content %}

trydjango19/templates/messages_display.html
{% if messages %}
    <div class="messages">
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>

</div>
{% endif %}

trydjango19/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head %}
    {{ instance.title }} | {{ block.super }}
{% endblock head %}
{% block post_detail_link %}
    <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}
<style>
    {% block style %}
        h1 {
            color: #777777;
        }
    {% endblock style %}
</style>
{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        {% if instance.image %}
            <img src="{{ instance.image.url }}" alt="" class='img-responsive'>
        {% endif %}
        <h1>{{ instance.title }}
            <small> {% if instance.draft %}
                <span style="color:red;">Draft </span>{% endif %}{{ instance.publish | timesince }}</small>
        </h1>
        <p>Readtime: {{ instance.read_time }} minutes</p>
        {% if instance.user.get_full_name %}
            <p>Author: {{ instance.user.get_full_name }}</p>
        {% endif %}

        <p>
        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like"
             data-size="small" data-show-faces="true" data-share="true"></div>
        </p>
        {#    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">#}
        {#Share on Facebook#}
        {#</a>#}
        {#    <a href="https://twitter.com/home?status={{ instance.content | urlify }}%20{{ request.build_absolute_uri }}">#}
        {#Share on Twitter#}
        {#</a>#}
        {#    <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'/>#}
        {#    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_ansolute_uri }}&title={{ instance.title }}&summary={{ share_tring }}&source={{ request.build_absolute_uri }}">#}
        {#Share on Linkedin#}
        {#</a>#}
        <hr/>
        <div class="row">
            <div class="post-detail-item">
                {{ instance.get_markdown }}
                <hr/>
                <br/>
                <div>
                    <h3 class="lead">Comments</h3>
                {% if request.user.is_authenticated %}
                    <form method="POST" action="."> {% csrf_token %}
                        {{ comment_form | crispy }}
                        <input type="submit" value="Post comment" class="btn btn-default">
                    </form>
                {% else %}
                <p> You must login to comment</p>
                {% endif %}
                    <hr/>

                    {% for comment in  comments %}
                        <blockquote>
                            <p>{{ comment.content }}</p>
                            <footer>via {{ comment.user }} | {{ comment.timestamp | timesince }} ago |
                                {% if comment.children.count > 0 %} {{ comment.children.count }} Comment
                                    {% if comment.children.count > 1 %}s{% endif %} |{% endif %}<a href=""
                                                                                                   class="comment-reply-btn">
                                    Reply</a> | <a href="{{ comment.get_absolute_url }}">Thread</a></footer>
                            <div class="comment-reply">
                                {% for child_comment in comment.children %}
                                    <blockquote>
                                        <p>{{ child_comment.content }}</p>
                                        <footer>via {{ child_comment.user }}
                                            | {{ child_comment.timestamp | timesince }}</footer>
                                    </blockquote>
                                {% endfor %}
                                 {% if request.user.is_authenticated %}
                                <form method="POST" action="."> {% csrf_token %}
                                    {{ comment_form | crispy }}
                                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                    <input type="submit" value="Reply" class="btn btn-default">
                                </form>
                            {% else %}
                <p> You must login to comment</p>
                {% endif %}
                            </div>
                        </blockquote>

                        <hr/>
                    {% endfor %}
                </div>
                {#    <div class="fb-comments" data-href="{{ request.build_ansolute_uri }}" data-numposts="5"></div>#}
            </div>
        </div>
    </div>
{% endblock content %}

trydjango19/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
    {{ form.media }}
{%  endblock head_extra %}
{% block content %}
    <div class="col-sm-6">
    <h1>Preview</h1>
        <hr/>
    <div class="content-preview">
    <h3 class="preview-title"></h3>
{#        <input id="preview-title">#}
    <p class="preview-content"></p>
    </div>
        </div>
    <div class="col-sm-6">
<h1>Form</h1>
<form method="POST" action="" enctype="multipart/form-data"> {% csrf_token %}
    {{ form|crispy}}
    <input type="submit" class='btn btn-default' value="Create Post"/>
</form>
    </div>
{% endblock content %}

trydjango19/templates/post_list.html
{% extends "base.html" %}
{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
    <div class="row">
        <h1>{{ title }}</h1>
        <form method="GET" action = "" class="row">
            <div class="col-sm-6">
            <div class="input-group">
                <input class="form-control" type="text" name = "q" placeholder="Search posts" value="{{ request.GET.q }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Search <i class="fa fa-search"></i></button>
                    </span>
            </div>
                </div>
        </form>
    <p></p>
</div>
    <div class="row">
{% for obj in object_list %}
    <div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
        <img src="{{ obj.image.url }}" alt="" class = 'img-responsive'/>
        {% endif %}
      <div class="caption post-detail-item">
      {% if obj.draft %}
          <h3>Draft  </h3>{% endif %}{% if obj.publish > today  %} <h3>Future Post</h3>{% endif %}


    <a href="{{ obj.get_absolute_url }}"> {{ obj.title }}</a><small>{{ obj.publish | timesince}}</small></h3>
          {% if obj.user.get_full_name %}
          <p>{{ obj.user.get_full_name }}</p>{% endif %}

        {{ obj.get_markdown | truncatechars_html:20}}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a> </p>
      </div>
    </div>
  </div>
    </hr>
    </div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
    </div>
    </div>
    {% endblock content %}